### ISSUE TITLE
Mysteams.tv user credentials do not work

### ISSUE THREAD

**Issue by dberg81** [stvhwrd/SmoothStreamsTV-playlist#16]
I updated the python script with my Mystreams username/password and the script fails saying the credentials are invalid.  I've tried setting the username with and without the full email address and I get the same behavior each time.  Screenshot attached.

![sstv-playlist error](https://cloud.githubusercontent.com/assets/19382179/20548209/5b4908a2-b0d6-11e6-8cc5-335061127d5b.PNG)

**Comment by stvhwrd** [comment]
Thanks @dberg81 for the feedback.  This is the same issue as existing Issue #8. I will close this Issue and prioritize the patch of #8.  In the meantime, try changing the `viewstvn` ([on line 88 in the latest version of the script](https://github.com/stvhwrd/SmoothStreamsTV-playlist/blob/master/sstv-playlist.py#L88)) to `viewms` or `mystreams`.

I don't yet have MyStreams.tv credentials to test with, so please let me know whether it worked!

Thanks again for the feedback.  Cheers
