### ISSUE TITLE
New Channels Released

### ISSUE THREAD

**Issue by athen66** [stvhwrd/SmoothStreamsTV-playlist#17]
Hey there, appreciate this script. SSTV just announced new channels:

https://www.reddit.com/r/SmoothStreamsTV/comments/5ptzvv/new_channels_available_on_smoothstreams/

Let me know if you need any help maintaining this.

**Comment by stvhwrd** [comment]
Hey @athen66 thanks for letting me know.  Help is always appreciated!  Feel free to submit a pull request.  Cheers 🍻

**Comment by stvhwrd** [comment]
Updated (at last) with commit b3ea3be70c8f949af5b1f82a8eebf8e866224d3e
