### ISSUE TITLE
List not working: File created but didn't work on VLC

### ISSUE THREAD

**Issue by columb1a** [stvhwrd/SmoothStreamsTV-playlist#20]
Hi. I successfully  created the list. So far so good. But the list is not working in vlc. 
I'm getting:
"Your input can't be opened: VLC is unable to open the MRL..."

**Comment by dbowles1975** [comment]
It's generating URLs for viewstvn instead of viewms. The auth token is correct but it's trying to use it for the wrong site.

**Comment by columb1a** [comment]
What do you mean? you mentioned two different things, the auth token and the server. Also I enter as a parameter viewms.

**Comment by dbowles1975** [comment]
When you enter your information into the script it should write a URL for each channel that contains an auth token, server, the site name and a link for that channel. The script is doing that BUT it appears to be entering the site as "viewstvn" (StreamTVNow) even though you've entered "viewms" (MyStreams). So the auth token is correct but it's being used on the wrong site. There's an error in the script.

**Comment by stvhwrd** [comment]
Hi guys,

Thanks for all the details.  I evidently didn't properly implement the handling of different hosts in the last update - I apologize for the inconvenience!  It's a quick fix and I'll have it done this morning.

Thanks @dbowles1975 for stepping up to help out!  Cheers 🍻
