### ISSUE TITLE
Unused Channels Crash Client

### ISSUE THREAD

**Issue by dbowles1975** [stvhwrd/SmoothStreamsTV-playlist#7]
Kodi PVR IPTV Simple Client - Clicking on an unused channel in the EPG causes Kodi to crash requiring a force stop. All other channels work just fine. How would I go about modifying the script so that playlist information is not added for unused channels? And is it possible to not add channel numbers so that I can use an xmltv file to automatically populate guide data?

**Comment by stvhwrd** [comment]
Hi @dbowles1975, 

Thanks for the question and sorry for the delay in responding.  The m3u8 that's generated is valid for all channels 1-120, though from the server side, not all channels are "up" 24/7.

The most straightforward way to exclude specific channels is to comment-out the channels you'd like to skip in the `channelDictionary` (currently on line 240).  In Python, comments are denoted by the hash symbol, `#`.

For example, if you wanted to skip channels 51-60, you'd change the lines in the script

``` python
...
   '46': 'Comedy Central',
   '47': 'AMC',
   '48': 'HBO East',
   '49': 'HBO Comedy',
   '50': 'HBO Signature',
   '51': 'HBO Zone',
   '52': 'ShowTime East',
   '53': 'ActionMax HD East',
   '54': 'Cinemax Moremax',
   '55': 'Starz Cinema',
   '56': 'Starz East',
   '57': '',
   '58': '',
   '59': 'Cinemax East',
   '60': 'Cinemax 5 Star',
   '61': '',
   '62': '',
   '63': '',
...
```

to

``` python
...
   '46': 'Comedy Central',
   '47': 'AMC',
   '48': 'HBO East',
   '49': 'HBO Comedy',
   '50': 'HBO Signature',
    # '51': 'HBO Zone',
    # '52': 'ShowTime East',
    # '53': 'ActionMax HD East',
    # '54': 'Cinemax Moremax',
    # '55': 'Starz Cinema',
    # '56': 'Starz East',
    # '57': '',
    # '58': '',
    # '59': 'Cinemax East',
    # '60': 'Cinemax 5 Star',
   '61': '',
   '62': '',
   '63': '',
...
```

The reason I chose to include all channels is that occasionally the unnamed channels do become active.

Without looking at your system/error logs I can only speculate that your Kodi PVR IPTV Simple Client (which I am not familiar with) is not properly handling the server's response to inactive channels, and consequently crashing.  Cheers
