### ISSUE TITLE
All SmoothStreams services not supported

### ISSUE THREAD

**Issue by Chaomino** [stvhwrd/SmoothStreamsTV-playlist#8]
Hi!

Im getting wrong login credentials every time i try to generate the file. Is the py file able to "log-in" on every SS site? My guessing is that the script is not signing me in in the right site. I use live247.

Also, if i edit the py file to add my credentials it gives me syntax error. I just put my user and pass inside the ''

Thanks for the effort you putting on it.

**Comment by stvhwrd** [comment]
Hi @Chaomino.  The script is currently hardcoded to use only [StreamTVNow](http://streamtvnow.tv/).  This is a valid issue, thanks for reporting it!  I will provide a fix shortly.

**Comment by Chaomino** [comment]
After a lot of tries i found the answer. Just changing the site to view247 and it worked!

Thank you very much

**Comment by stvhwrd** [comment]
Glad you found a temporary fix.  I will add support for all services in the proper fix.  I didn't initially realize that there were so many services that fell under the SmoothStreams umbrella.

These services include:

| Service | Site |
| --- | --- |
| MyStreams | `viewms`, `mystreams` |
| Live247 | `view247`, `live247` |
| StarStreams | `viewss`, `starstreams` |
| StreamTVNow | `viewstvn` |
| MMA-TV / MyShout | `mma-tv` |

**Comment by bradmurray** [comment]
This is fixed in the pull request that I just submitted.

**Comment by fsegouin** [comment]
@stvhwrd You would also need to change the channel url generated, it's currently hardcoded to `viewstvn`.

**Comment by stvhwrd** [comment]
Closed by commit db721ee9cba27fce9aa90e1a95cb84907064accc
